[pytest]

markers =
    smoke: Critical tests for basic application functionality
    regression: Tests covering broader application functionality

reruns = 1
reruns_delay = 1

addopts =
    -v
    --strict-markers

# without using strict markers if someone right smkoe instead of smoke the it will get unnoticed